[project]
name = "project2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
package-mode = false
requires-python = ">=3.11"
dependencies = [
    "openai>=1.84.0",
    "pypdf2>=3.0.1",
    "python-dotenv>=1.1.0",
    "streamlit>=1.45.1",
]
