name: My OpenAI Python Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x' # Consider being more specific, e.g., '3.10'

      - name: Install dependencies
        run: | # Use a multi-line run command for clarity if you have many packages
          pip install openai python-dotenv streamlit # <--- ADDED streamlit HERE
          # If you have a requirements.txt file, this is even better:
          # pip install -r requirements.txt

      - name: Run script
        # Assuming your script is now correctly named main.py
        run: python main.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
