name: My OpenAI Python Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x' # Consider being more specific, e.g., '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install streamlit PyPDF2 openai python-dotenv  # <--- THESE ARE THE PACKAGES

      - name: Run script
        run: python main.py # Or whatever your main script is
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
